/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        /* Jal Seva brand colors */
        "water-blue": "#4FC3F7",
        "warm-brown": "#8D6E63",
        "water-blue-dark": "#0288D1",
        "water-blue-light": "#B3E5FC",
        "warm-brown-dark": "#6D4C41",
        "warm-brown-light": "#BCAAA4",
        /* Legacy tokens kept for other pages */
        "tertiary": "#5f5e5e",
        "outline-variant": "#bdc8d0",
        "error": "#ba1a1a",
        "surface-container-high": "#e4e9ed",
        "on-surface": "#171c1f",
        "secondary": "#75584d",
        "on-surface-variant": "#3e484f",
        "secondary-fixed": "#ffdbce",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#e4beb2",
        "primary-fixed-dim": "#75d1ff",
        "surface-container": "#eaeef3",
        "surface-dim": "#d6dadf",
        "on-secondary-fixed-variant": "#5b4137",
        "inverse-on-surface": "#edf1f5",
        "tertiary-fixed": "#e4e2e1",
        "outline": "#6e7980",
        "error-container": "#ffdad6",
        "surface": "#f6fafe",
        "on-primary-container": "#004e69",
        "primary-container": "#4fc3f7",
        "secondary-container": "#fed7ca",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#2b160f",
        "on-background": "#171c1f",
        "tertiary-container": "#b9b7b7",
        "primary-fixed": "#c2e8ff",
        "surface-bright": "#f6fafe",
        "inverse-surface": "#2c3134",
        "surface-variant": "#dfe3e7",
        "inverse-primary": "#75d1ff",
        "primary": "#006688",
        "surface-tint": "#006688",
        "on-tertiary-container": "#484848",
        "on-primary-fixed-variant": "#004d67",
        "surface-container-low": "#f0f4f8",
        "background": "#f6fafe",
        "surface-container-highest": "#dfe3e7",
        "tertiary-fixed-dim": "#c8c6c6",
        "on-secondary-container": "#795c51",
        "on-primary-fixed": "#001e2b",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#474747",
        "on-tertiary-fixed": "#1b1c1c"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "base": "8px",
        "stack-lg": "24px",
        "stack-sm": "4px",
        "container-margin-mobile": "16px",
        "section-gap": "40px",
        "gutter": "16px",
        "stack-md": "12px",
        "container-margin-desktop": "48px"
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
